@extends('layouts.admin')

@section('content')
<div x-data="nivelaciones()" x-init="init()" x-cloak>
    <div class="page-header"><div><h1 class="page-title">Nivelaciones</h1><p class="page-subtitle">Resultados de exámenes PEX ya aprobados</p></div><button @click="cargar()" class="btn btn-outline btn-sm">Actualizar</button></div>
    <div x-show="error" class="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700" x-text="error"></div>
    <div class="card"><div class="table-container"><table class="table"><thead><tr><th>Estudiante</th><th>Examen</th><th>Período</th><th>Estado</th><th></th></tr></thead><tbody>
        <template x-for="m in pendientes" :key="m.id"><tr><td x-text="m.estudiante?.codigo + ' · ' + m.estudiante?.nombre + ' ' + m.estudiante?.apellido"></td><td x-text="m.oferta_academica?.codigo"></td><td x-text="m.oferta_academica?.periodo_academico?.nombre"></td><td><span class="badge badge-warning">Pendiente</span></td><td class="text-right"><button x-show="api.hasPermission('nivelaciones.crear')" @click="abrir(m)" class="btn btn-primary btn-sm">Registrar resultado</button></td></tr></template>
        <tr x-show="!loading && pendientes.length===0"><td colspan="5" class="py-8 text-center text-gray-400">No hay exámenes pendientes de evaluar.</td></tr>
    </tbody></table></div></div>
    <div class="card mt-6"><div class="card-header"><h2 class="font-semibold">Historial de resultados</h2></div><div class="table-container"><table class="table"><thead><tr><th>Estudiante</th><th>Examen</th><th>Resultado</th><th>Nivel recomendado</th><th></th></tr></thead><tbody><template x-for="e in evaluaciones" :key="e.id"><tr><td x-text="e.estudiante?.codigo+' · '+e.estudiante?.nombre+' '+e.estudiante?.apellido"></td><td x-text="e.oferta_examen?.codigo"></td><td><span class="badge" :class="e.estado==='aprobada'?'badge-success':e.estado==='rechazada'?'badge-danger':'badge-neutral'" x-text="e.estado"></span></td><td x-text="e.nivel_recomendado?.nombre||'—'"></td><td class="text-right"><button x-show="e.estado!=='anulada'&&api.hasPermission('nivelaciones.anular')" @click="anular(e)" class="btn btn-outline btn-sm text-red-700">Anular</button></td></tr></template><tr x-show="!loading&&evaluaciones.length===0"><td colspan="5" class="py-6 text-center text-gray-400">Aún no hay resultados registrados.</td></tr></tbody></table></div></div>
    <div x-show="modal" class="fixed inset-0 z-50 flex items-center justify-center p-4"><div class="absolute inset-0 bg-black/50" @click="modal=false"></div><form @submit.prevent="guardar()" class="relative w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl space-y-4"><h2 class="text-lg font-semibold">Resultado de nivelación</h2><p class="text-sm text-gray-500" x-text="seleccion?.estudiante?.nombre + ' ' + seleccion?.estudiante?.apellido"></p><div><label class="label">Nota</label><input x-model.number="form.nota_obtenida" type="number" min="0" max="100" required class="input"></div><label class="flex gap-2 text-sm"><input x-model="form.aprobado" type="checkbox"> Aprobó el examen</label><div x-show="form.aprobado"><label class="label">Último nivel acreditado</label><select x-model="form.nivel_acreditado_id" :required="form.aprobado" class="input"><option value="">Seleccionar...</option><template x-for="n in nivelesElegibles" :key="n.id"><option :value="n.id" x-text="n.codigo + ' · ' + n.nombre"></option></template></select><p class="mt-1 text-xs text-gray-500">El sistema calculará el siguiente nivel recomendado.</p></div><div><label class="label">Observaciones</label><textarea x-model="form.observaciones" class="input" rows="3"></textarea></div><div class="flex justify-end gap-2"><button type="button" @click="modal=false" class="btn btn-outline">Cancelar</button><button :disabled="guardando" class="btn btn-primary" x-text="guardando?'Guardando...':'Guardar resultado'"></button></div></form></div>
</div>
@endsection

@section('scripts')
<script>
function nivelaciones(){return {pendientes:[],evaluaciones:[],niveles:[],loading:false,guardando:false,modal:false,error:'',seleccion:null,form:{},async init(){await this.cargar()},async cargar(){this.loading=true;this.error='';const h={headers:{Authorization:`Bearer ${localStorage.getItem('auth_token')}}};try{const p=await window.axios.get('/api/v1/nivelaciones/pendientes',h);this.pendientes=p.data.data.data||[];const [e,n]=await Promise.allSettled([window.axios.get('/api/v1/nivelaciones',h),window.axios.get('/api/v1/catalogos-academicos/niveles-academicos',h)]);if(e.status==='fulfilled')this.evaluaciones=e.value.data.data.data||[];if(n.status==='fulfilled')this.niveles=n.value.data.data.data||n.value.data.data||[];if(e.status==='rejected'||n.status==='rejected')this.error='Se cargaron los exámenes pendientes; no fue posible cargar todo el historial o catálogo.'}catch(e){this.error=window.extractError(e,'No fue posible cargar los exámenes pendientes')}finally{this.loading=false}},get nivelesElegibles(){const version=this.seleccion?.oferta_academica?.nivel_academico?.version_plan_estudio_id;return this.niveles.filter(n=>String(n.version_plan_estudio_id)===String(version)&&n.id!==this.seleccion?.oferta_academica?.nivel_academico_id)},abrir(m){this.seleccion=m;this.form={nota_obtenida:'',aprobado:false,nivel_acreditado_id:'',observaciones:''};this.modal=true},async guardar(){this.guardando=true;this.error='';try{const h={headers:{Authorization:`Bearer ${localStorage.getItem('auth_token')}}};const payload={...this.form,matricula_examen_id:this.seleccion.id};if(!payload.aprobado)delete payload.nivel_acreditado_id;await window.axios.post('/api/v1/nivelaciones/registrar',payload,h);this.modal=false;await this.cargar();window.dispatchEvent(new CustomEvent('show-toast',{detail:{message:'Resultado registrado',type:'success'}}))}catch(e){this.error=window.extractError(e,'No fue posible registrar el resultado')}finally{this.guardando=false}},async anular(e){const motivo=window.prompt('Indique el motivo de la anulación:');if(!motivo)return;try{await window.axios.post(`/api/v1/nivelaciones/${e.id}/anular`,{motivo_anulacion:motivo},{headers:{Authorization:`Bearer ${localStorage.getItem('auth_token')}}});await this.cargar();window.dispatchEvent(new CustomEvent('show-toast',{detail:{message:'Resultado anulado',type:'success'}}))}catch(error){this.error=window.extractError(error,'No fue posible anular el resultado')}}}}
</script>
@endsection
